export const DEFAULT_INITIAL_BLACK_POSITION: string[][] = [
  [
    'white-rook',
    'white-knight',
    'white-bishop',
    'white-king',
    'white-queen',
    'white-bishop',
    'white-knight',
    'white-rook',
  ],
  [
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
  ],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  [
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
  ],
  [
    'black-rook',
    'black-knight',
    'black-bishop',
    'black-king',
    'black-queen',
    'black-bishop',
    'black-knight',
    'black-rook',
  ],
];

export const DEFAULT_INITIAL_WHITE_POSITION: string[][] = [
  [
    'black-rook',
    'black-knight',
    'black-bishop',
    'black-queen',
    'black-king',
    'black-bishop',
    'black-knight',
    'black-rook',
  ],
  [
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
    'black-pawn',
  ],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  ['', '', '', '', '', '', '', ''],
  [
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
    'white-pawn',
  ],
  [
    'white-rook',
    'white-knight',
    'white-bishop',
    'white-queen',
    'white-king',
    'white-bishop',
    'white-knight',
    'white-rook',
  ],
];
